apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsl-nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
       app: nginx
  template:
     metadata:
        labels:
           app: nginx
     spec:
       containers:
          - name: nginx
            image: "680532354232.dkr.ecr.us-east-1.amazonaws.com/saranecrrepo"
            ports:
              - containerPort: 8080
       imagePullSecrets:
                 -  name: regcred
